# Generated by Django 4.2.1 on 2023-06-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_alter_customerprogress_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprogress',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.salesperson'),
        ),
    ]
