# Generated by Django 4.2.1 on 2023-06-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_remove_customerprogress_sale_sale_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='customerprogress',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.sale'),
        ),
    ]
