# Generated by Django 4.2.1 on 2023-06-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_remove_sale_customer_remove_sale_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='local',
            field=models.IntegerField(choices=[(1, '北區'), (2, '中區'), (3, '南區')], default=1),
        ),
    ]
