# Generated by Django 4.2.1 on 2023-06-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_branch_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('Inventory_name', models.CharField(max_length=100)),
                ('Inventory_quantity', models.IntegerField(default=0)),
                ('Inventory_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventory_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '庫存',
                'verbose_name_plural': '庫存',
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_volume',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.inventory'),
        ),
    ]
