# Generated by Django 4.2.1 on 2023-06-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_delete_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(db_index=True)),
                ('Quantity', models.IntegerField(default=1)),
                ('Inventory_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APP.inventory')),
            ],
            options={
                'verbose_name': '進貨',
                'verbose_name_plural': '進貨',
            },
        ),
        migrations.CreateModel(
            name='Public_Massage_chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True)),
                ('Inventory_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APP.inventory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.customer')),
            ],
            options={
                'verbose_name': '公共按摩椅體驗',
                'verbose_name_plural': '公共按摩椅體驗',
            },
        ),
    ]
