# Generated by Django 4.2.1 on 2023-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_purchases_public_massage_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_massage_chair',
            name='feedback',
            field=models.IntegerField(choices=[(1, '滿意'), (2, '不滿意')], default=1),
        ),
    ]
