# Generated by Django 4.2.1 on 2023-06-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_public_massage_chair_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Inventory_quantity',
        ),
    ]
