# Generated by Django 4.2.1 on 2023-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_remove_inventory_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprogress',
            name='progress_status',
            field=models.IntegerField(choices=[(1, '申辦會員'), (2, '體驗按摩椅'), (3, '購買完成')], default=1),
        ),
    ]
