# Generated by Django 4.2.1 on 2023-06-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_alter_customerprogress_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprogress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerprogress',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='customerprogress',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='public_massage_chair',
            name='Inventory_id',
        ),
        migrations.RemoveField(
            model_name='public_massage_chair',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='Inventory_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerProgress',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Public_Massage_chair',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Salesperson',
        ),
    ]
