# Generated by Django 4.2.1 on 2023-06-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BRANCH',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='public_massage_chair',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='public_massage_chair',
            name='Seller',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Seller',
        ),
        migrations.DeleteModel(
            name='CUSTOMER',
        ),
        migrations.DeleteModel(
            name='PRODUCT',
        ),
        migrations.DeleteModel(
            name='PRODUCT_MODEL',
        ),
        migrations.DeleteModel(
            name='PUBLIC_MASSAGE_CHAIR',
        ),
        migrations.DeleteModel(
            name='SALE',
        ),
        migrations.DeleteModel(
            name='SELLER',
        ),
    ]
