# Generated by Django 4.2.1 on 2023-06-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='branch',
            new_name='Branch',
        ),
    ]
