# Generated by Django 4.2.1 on 2023-06-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0021_rename_branch_sale_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_massage_chair',
            name='Feedback',
            field=models.IntegerField(choices=[(1, '滿意'), (2, '不滿意')], default=1),
        ),
        migrations.AddField(
            model_name='public_massage_chair',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.product'),
        ),
    ]
