# Generated by Django 4.2.1 on 2023-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_public_massage_chair_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_massage_chair',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.product'),
        ),
    ]
